version: '3.7'
services:

  database:
    container_name: indexer-database
    image: postgres:9.6
    env_file:
      - dev.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - indexer-net

  api:
    container_name: indexer-api
    build: .
    command: ["sh","script/sh/entrypoint"]
    ports:
      - 3000:3000
    networks:
      - indexer-net
    env_file:
      - dev.env
    volumes:
      - .:/api
      - bundle-cache:/usr/local/bundle
    depends_on:
      - database

volumes:
  pg-data:
  bundle-cache:

networks: 
  indexer-net:
    name: indexer-net
